GET http://localhost:3000/department
####

GET http://localhost:3000/getOnePosition/1
####

GET http://localhost:3000/user
####

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "admin",
    "status": 1,
    "password": '12345',
    "confirmPassword": '12345',
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
        "name": "admin",
        "password": "12345"
      }

###
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwic3RhdHVzIjoxLCJpYXQiOjE2NjU5MDU0MDYsImV4cCI6MTY2NTkwNTQyMX0.cFFWJVLtKZCVe3suJMoLDJ5NDDbqsb5XpyOVG47g9_0

###
GET http://localhost:3000/token

###
DELETE http://localhost:3000/logout

###
POST http://localhost:3000/searchPosition
Content-Type: application/json

{
        "search": "engineering manager"
      }

###
POST http://localhost:3000/department
Content-Type: application/json

[{
        "name": "Engineering",
        "status": 1,
        "order": 1,
        "groupId": 1,
      }]

###
GET http://localhost:3000/department
###
POST http://localhost:3000/group
Content-Type: application/json

[{
  "description": "Client7"
},
{
  "description": "Client8"
}]

###
GET http://localhost:3000/group
###
GET http://localhost:3000/group/232
###
POST http://localhost:3000/searchGroup
Content-Type: application/json

{
        "search": "client"
      }

###
PATCH http://localhost:3000/group/232
Content-Type: application/json

{
        "description": "Wasco2"
      }
###
DELETE http://localhost:3000/group/190

###
DELETE http://localhost:3000/multipleDeleteGroup
Content-Type: application/json

{
  "id": [225]
}
